# Generated by Django 4.2 on 2023-05-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTemplate',
            new_name='XaviNino',
        ),
    ]
