# Generated by Django 4.2 on 2025-06-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cobrament',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
