# Generated by Django 4.2 on 2025-06-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pistes',
            old_name='tipus',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='pista',
            new_name='cancha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='horaFinalitzacio',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='horaInici',
            new_name='hora_inicio',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('cancha', 'fecha', 'hora_inicio')},
        ),
        migrations.AddField(
            model_name='pistes',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padel_admin.recepcionista'),
        ),
    ]
