# Generated by Django 4.2 on 2025-06-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0002_rename_tipus_pistes_tipo_rename_pista_reserva_cancha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.pistes')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.jugadors')),
            ],
        ),
    ]
