# Generated by Django 4.2 on 2025-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0003_reservarecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadors',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_jugadores/'),
        ),
    ]
