# Generated by Django 4.2 on 2023-05-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0003_xavierito_delete_xavinino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xavierito',
        ),
    ]
