# Generated by Django 4.2 on 2025-06-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0004_jugadors_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
