# Generated by Django 4.2 on 2023-05-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='CobramentSoci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadors',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('cognom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telefon', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('tipus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horaInici', models.TimeField()),
                ('horaFinalitzacio', models.TimeField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.jugadors')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.pistes')),
            ],
            options={
                'unique_together': {('jugador', 'data')},
            },
        ),
        migrations.DeleteModel(
            name='Xavierito',
        ),
        migrations.CreateModel(
            name='Soci',
            fields=[
                ('jugadors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='padel_admin.jugadors')),
                ('IBAN', models.CharField(max_length=34)),
            ],
            bases=('padel_admin.jugadors',),
        ),
        migrations.AddField(
            model_name='cobrament',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.jugadors'),
        ),
        migrations.AddField(
            model_name='cobrament',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.reserva'),
        ),
        migrations.AddField(
            model_name='cobramentsoci',
            name='soci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.soci'),
        ),
    ]
