# Generated by Django 4.2 on 2025-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0005_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
