# Generated by Django 4.2 on 2025-06-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0006_alter_tarifa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrament',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
