# Generated by Django 4.2 on 2025-06-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0007_alter_cobrament_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('pago', 'Pago realizado'), ('cancelacion', 'Reserva cancelada')], max_length=20)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.jugadors')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_admin.reserva')),
            ],
        ),
    ]
