# Generated by Django 4.2 on 2025-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0008_historicoreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoreserva',
            name='accion',
            field=models.CharField(choices=[('pago', 'Pago realizado'), ('cancelacion', 'Reserva cancelada'), ('devolucion', 'Devolución realizada')], max_length=20),
        ),
    ]
