# Generated by Django 4.2 on 2023-05-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobramentsoci',
            name='soci',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pista',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='recepcionista',
        ),
        migrations.RemoveField(
            model_name='soci',
            name='jugadors_ptr',
        ),
        migrations.DeleteModel(
            name='Cobrament',
        ),
        migrations.DeleteModel(
            name='CobramentSoci',
        ),
        migrations.DeleteModel(
            name='Jugadors',
        ),
        migrations.DeleteModel(
            name='Pistes',
        ),
        migrations.DeleteModel(
            name='Recepcionista',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Soci',
        ),
    ]
