# Generated by Django 4.2 on 2025-06-13 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0009_alter_historicoreserva_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadors',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cobrament',
            index=models.Index(fields=['reserva'], name='padel_admin_reserva_db6830_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrament',
            index=models.Index(fields=['jugador'], name='padel_admin_jugador_2a7916_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoreserva',
            index=models.Index(fields=['reserva'], name='padel_admin_reserva_f8cd48_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoreserva',
            index=models.Index(fields=['jugador'], name='padel_admin_jugador_f3cc02_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoreserva',
            index=models.Index(fields=['fecha'], name='padel_admin_fecha_021956_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha'], name='padel_admin_fecha_6a5051_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['jugador'], name='padel_admin_jugador_8511a6_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cancha'], name='padel_admin_cancha__71382a_idx'),
        ),
    ]
