# Generated by Django 4.2 on 2025-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0011_producto_proveedor_venta_ventadetalle_ingresostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único de identificación', max_length=20, null=True, unique=True),
        ),
    ]
