# Generated by Django 4.2 on 2023-05-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadors',
            name='telefon',
            field=models.CharField(max_length=16),
        ),
    ]
