# Generated by Django 4.2 on 2023-05-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_admin', '0031_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadors',
            name='telefon',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='recepcionista',
            name='telefon',
            field=models.CharField(max_length=13),
        ),
    ]
